"""add import batch sprint2 fields

Revision ID: 92b8bc3adcb7
Revises: 573d50d9ff0e
Create Date: 2026-04-06 11:01:49.993815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b8bc3adcb7'
down_revision = '573d50d9ff0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_catalog_properties_address_full', table_name='catalog_properties')
    op.drop_index('ix_catalog_properties_is_active', table_name='catalog_properties')
    op.add_column('import_batches', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('import_batches', sa.Column('error_message', sa.String(length=1000), nullable=True))
    op.drop_index('ix_import_batches_created_at', table_name='import_batches')
    op.drop_index('ix_import_batches_status', table_name='import_batches')
    op.drop_index('ix_property_analytics_source_type', table_name='property_analytics')
    op.create_index(op.f('ix_property_analytics_version'), 'property_analytics', ['version'], unique=False)
    op.drop_constraint('fk_property_analytics_catalog_property_id', 'property_analytics', type_='foreignkey')
    op.create_foreign_key(None, 'property_analytics', 'catalog_properties', ['catalog_property_id'], ['id'])
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_constraint(None, 'property_analytics', type_='foreignkey')
    op.create_foreign_key('fk_property_analytics_catalog_property_id', 'property_analytics', 'catalog_properties', ['catalog_property_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_property_analytics_version'), table_name='property_analytics')
    op.create_index('ix_property_analytics_source_type', 'property_analytics', ['source_type'], unique=False)
    op.create_index('ix_import_batches_status', 'import_batches', ['status'], unique=False)
    op.create_index('ix_import_batches_created_at', 'import_batches', ['created_at'], unique=False)
    op.drop_column('import_batches', 'error_message')
    op.drop_column('import_batches', 'updated_at')
    op.create_index('ix_catalog_properties_is_active', 'catalog_properties', ['is_active'], unique=False)
    op.create_index('ix_catalog_properties_address_full', 'catalog_properties', ['address_full'], unique=False)
    # ### end Alembic commands ###
